apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  namespace: demo
data:
  application.properties: |
    greeting.message=Say Hello to the World outside
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: kubernetes-fabric8-config-example:3.1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          args: ["--spring.config.location=application.properties"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: demo-config
              mountPath: /opt/application.properties
              subPath: application.properties
      volumes:
        - name: demo-config
          configMap:
            name: demo-configmap
            items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32123
  selector:
    app: demo
