---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: kubernetes-fabric8-config-example
      name: kubernetes-fabric8-config-example
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: kubernetes-fabric8-config-example
      type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: kubernetes-fabric8-config-example
      name: kubernetes-fabric8-config-example
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: kubernetes-fabric8-config-example
      template:
        metadata:
          labels:
            app: kubernetes-fabric8-config-example
        spec:
          serviceAccountName: config-reader
          containers:
            - name: kubernetes-fabric8-config-example
              image: org/kubernetes-fabric8-config-example:3.1.0-SNAPSHOT
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080
              env:
                - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
                  value: "true"
                - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
                  value: "true"
              securityContext:
                privileged: false
